version: '3.0'
services:
    flask:
      build: .
      container_name: flask
      ports:
        - "5000:5000"
      volumes:
        - "./src:/projects"
      env_file: ./env
      tty: true
      environment:
        TZ: Asia/Tokyo
      cap_add:
        - SYS_RAWIO
      privileged: true
      tty: true
      devices:
          - /dev/mem
          - /dev/vcio
          - /dev/ttyAMA0
      command: sh -c "pigpiod && flask run --host 0.0.0.0 --port 5000"
